// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4fhNegTqsTXkLuyOG33F8bh-PH0g5PDE',
    appId: '1:777467227554:web:7e2d9dabb53897a3a396fb',
    messagingSenderId: '777467227554',
    projectId: 'bootcampmaterial-8f04b',
    authDomain: 'bootcampmaterial-8f04b.firebaseapp.com',
    storageBucket: 'bootcampmaterial-8f04b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYTuK7JhkZHxah6_D7I9B6qtPxKarO24',
    appId: '1:777467227554:android:40a6ec149f6016a3a396fb',
    messagingSenderId: '777467227554',
    projectId: 'bootcampmaterial-8f04b',
    storageBucket: 'bootcampmaterial-8f04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbmHnNiv8FRZRD--plMCvmbuPjXVjBLzc',
    appId: '1:777467227554:ios:9a2ab60870fec5f9a396fb',
    messagingSenderId: '777467227554',
    projectId: 'bootcampmaterial-8f04b',
    storageBucket: 'bootcampmaterial-8f04b.appspot.com',
    iosClientId: '777467227554-q11nkhm07p44qrj8r6cljsc07gf7fjhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkingHttp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbmHnNiv8FRZRD--plMCvmbuPjXVjBLzc',
    appId: '1:777467227554:ios:9a2ab60870fec5f9a396fb',
    messagingSenderId: '777467227554',
    projectId: 'bootcampmaterial-8f04b',
    storageBucket: 'bootcampmaterial-8f04b.appspot.com',
    iosClientId: '777467227554-q11nkhm07p44qrj8r6cljsc07gf7fjhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkingHttp',
  );
}
